#配置数据库的链接
spring:
  application:
    name: 网页通信

  datasource:
    url: jdbc:mysql://localhost:3306/网页通信?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      timeout: 3000ms


#mybatis配置
mybatis:
  configuration:
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true
  #自定义存放路径
  mapper-locations: classpath:org/web03/mapper/*.xml



#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
